spring:
  mvc:
    problemdetails:
      enabled: true
  data:
    rest:
      base-path: "/api"
  jpa:
    database: "mysql"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
